version: '3'

tasks:
  01-create-namespace:
    cmds:
      - kubectl config use-context mrupgradable-octal
      - kubectl apply -f k8s/namespace/namespace.yml
  02-create-namespace-context:
    cmds:
      - kubectl config set-context mrupgradable-octal-experimental --cluster=octal --namespace=experimental --user=mrupgradable.senary
  03-change-to-namespace-context:
    cmds:
      - kubectl config get-contexts
      - kubectl config use-context mrupgradable-octal-experimental
      - kubectl config get-contexts
  04-deploy:
    cmds:
      - kubectl apply -f k8s/deployment/deployment.yml
  05-list-deployments:
    cmds:
      - kubectl get deployments
  06-describe-deployment:
    cmds:
      - kubectl describe deployment nginx-deployment
  07-list-pods:
    cmds:
      - kubectl get pods
  08-scale-up-manually:
    cmds:
      - kubectl scale deployment/nginx-deployment --replicas=10
  09-scale-down-manually:
    cmds:
      - kubectl scale deployment/nginx-deployment --replicas=1
  10-create-hpa-autoscale:
    cmds:
      - kubectl apply -f k8s/scale/hpa.yml
  11-describe-hpa-autoscala:
    cmds:
      - kubectl describe hpa nginx-hpa
  12-list-hap-autoscale:
    cmds:
      - kubectl get hpa
  13-expose-service:
    cmds:
      - kubectl apply -f k8s/service/service.yml
  14-delete-service:
    cmds:
      - kubectl delete service experimental-service
