apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom:cluster-maintainer
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "update", "get", "list", "watch", "delete"]
