apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mrupgradable:role-binding
  namespace: experimental
subjects:
- kind: User           
  name: mrupgradable.senary   
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-admin
  apiGroup: rbac.authorization.k8s.io
