apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: experimental
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

