apiVersion: v1
kind: Service
metadata:
  name: experimental-service
  namespace: experimental
spec:
  externalIPs: 
    - 192.168.8.80
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

